name: Bug report
description: Report a bug in the software.
labels: bug

body:
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide instructions on how to reproduce the bug.
      placeholder: |-
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please provide a clear and concise description of what you expected to happen.
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Additional information
      description: Add here any other information you think may be relevant to the problem.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/orryverducci/StreamSDR/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
